// language definition
WHITESPACE = _{ " " | "\t" | "\n" | "\r" }
COMMENT    = _{ ("/*" ~ (!"*/" ~ ANY)* ~ "*/") | ("//" ~ (!"\n" ~ ANY)*) }

// primitive tokens
type_ = {
    "Int"
  | "Bool"
  | "Unit" // equivalent to rust (), python None, (sort of) java null
}

// keywords (prevent them from being identifiers)
KEYWORD = { "if" | "then" | "else" | "let" | "def" | "true" | "false" | "Unit" | "Int" | "Bool" | "while" | "do" | "module" | "mut" }

identifier       = @{ !(KEYWORD ~ !(ASCII_ALPHANUMERIC | "_")) ~ "_"* ~ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }
empty_identifier = @{ "_" }

number = @{ ASCII_DIGIT+ }

boolean = @{ "true" | "false" }

// binary_operand = _{ add | subtract | multiply | divide | power | and | or | xor }

unary_operand = { subtract | negate }

add      = { "+" }
subtract = { "-" }
multiply = { "*" }
divide   = { "/" }
pow      = { "^" }
negate   = { "!" }
and      = { "&" }
or       = { "|" }
xor      = { "⊕" | "#" }
gt       = { ">" }
lt       = { "<" }
ne       = { "≠" | "!=" }
eq       = { "==" }
ge       = { ">=" | "≥" }
le       = { "<=" | "≤" }

// language is built around expressions,
ifstatement = {
    "if" ~ expression ~ "then" ~ expression ~ ("else" ~ expression)?
}

whileloop = {
    "while" ~ expression ~ "do" ~ expression
}

function_call          = { identifier ~ "(" ~ (expression ~ ("," ~ expression)*)? ~ ")" }
external_function_call = { identifier ~ "::" ~ identifier ~ "(" ~ (expression ~ ("," ~ expression)*)? ~ ")" }

// precedence chaining
primary = {
    ("(" ~ expression ~ ")")
  | ifstatement
  | whileloop
  | function_call
  | external_function_call
  | number
  | boolean
  | identifier
  | ("{" ~ statement* ~ expression? ~ "}")
}

unary      = { (unary_operand ~ unary) | primary }
power      = { unary ~ (pow ~ power)? }
mul_div    = { power ~ ((multiply | divide) ~ power)* }
add_sub    = { mul_div ~ ((add | subtract) ~ mul_div)* }
comparison = { add_sub ~ ((ge | le | gt | lt) ~ add_sub)* }
equality   = { comparison ~ ((eq | ne) ~ comparison)* }
logic_and  = { equality ~ (and ~ equality)* }
logic_xor  = { logic_and ~ (xor ~ logic_and)* }
logic_or   = { logic_xor ~ (or ~ logic_xor)* }
expression = { logic_or }

mut_kw = { "mut" }

// variables
declaration = { "let" ~ mut_kw? ~ (identifier | empty_identifier) ~ (":" ~ type_)? ~ "=" ~ expression }

// left here for later:
// constant = { "const" ~ declaration }
// mutable = { "mut" ~ declaration }

assignment = { identifier ~ "=" ~ expression }

// statements are the imperative elements of the language
statement = {
    ((declaration | assignment | expression) ~ ";")
}

// functions are highest-order tokens
parameter  = { mut_kw? ~ (identifier | empty_identifier) ~ ":" ~ type_ }
parameters = { parameter ~ ("," ~ parameter)* ~ ","? }

function = { "def" ~ identifier ~ "(" ~ parameters? ~ ")" ~ ":" ~ type_ ~ ":=" ~ expression }

module = { "module" ~ identifier ~ ";"? }

program = { SOI ~ (function | module)* ~ EOI }
